find_unused_parameters: True
use_focal_loss: True
clip_max_norm: 0.1
epoches: 200
sync_bn: True

use_ema: True
ema:
  type: ModelEMA
  decay: 0.9999
  warmups: 2000

scaler:
  type: GradScaler
  enabled: True

optimizer:
  type: AdamW
  lr: 0.0001
  betas: [0.9, 0.999]
  weight_decay: 0.0001

lr_scheduler:
  type: MultiStepLR
  milestones: [1000]
  gamma: 0.1